### ISSUE TITLE
Does not work with my Samsung TV.

### ISSUE THREAD

**Issue by Ingvix** [colindunn/kodi-cec-off-screensaver#1]
Not sure if this is just some small addon for your own use but I hope you could make this work for me too or help me to make it work for me. The Kodi's native function to turn tv off when screensaver activates doesn't work for me. Here's the error:

> 23:30:15.036 T:140175888893696   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'urllib2.URLError'>
>                                             Error Contents: <urlopen error [Errno 111] Connection refused>
>                                             Traceback (most recent call last):
>                                               File "/home/qbtuser/.kodi/addons/net.vikingdev.kodi.cec-tv-off.screensaver/screensaver.py", line 23, in onInit
>                                                 urllib2.urlopen('http://127.0.0.1:8891').read()
>                                               File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>                                                 return opener.open(url, data, timeout)
>                                               File "/usr/lib/python2.7/urllib2.py", line 429, in open
>                                                 response = self._open(req, data)
>                                               File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>                                                 '_open', req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                                 result = func(*args)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
>                                                 return self.do_open(httplib.HTTPConnection, req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>                                                 raise URLError(err)
>                                             URLError: <urlopen error [Errno 111] Connection refused>
>                                             -->End of Python script error report<--

**Comment by colindunn** [comment]
This is specifically calling something on my kodi host and is specific to my setup. I'd recommend you look at a different solution sorry. This one looks good: https://github.com/dagwieers/screensaver.turnoff
